// <auto-generated />
using System;
using Exercise3.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exercise3.Data.Migrations
{
    [DbContext(typeof(Exercise3DbContext))]
    partial class Exercise3DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Exercise3.Data.Entities.Agreements", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AgreementName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgreementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DaysUntilExpiration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistributorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuoteNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Agreements", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgreementName = "Name 2",
                            AgreementType = "Name 3",
                            CreatedDate = new DateTime(2022, 5, 24, 16, 16, 58, 638, DateTimeKind.Local).AddTicks(8900),
                            DaysUntilExpiration = "Name 5",
                            DistributorName = "Name 4",
                            EffectiveDate = new DateTime(2022, 5, 24, 16, 16, 58, 638, DateTimeKind.Local).AddTicks(8888),
                            ExpirationDate = new DateTime(2022, 5, 24, 16, 16, 58, 638, DateTimeKind.Local).AddTicks(8900),
                            QuoteNumber = "Name 1",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            AgreementName = "Name 3",
                            AgreementType = "Name 4",
                            CreatedDate = new DateTime(2022, 5, 24, 16, 16, 58, 638, DateTimeKind.Local).AddTicks(8904),
                            DaysUntilExpiration = "Name 6",
                            DistributorName = "Name 5",
                            EffectiveDate = new DateTime(2022, 5, 24, 16, 16, 58, 638, DateTimeKind.Local).AddTicks(8903),
                            ExpirationDate = new DateTime(2022, 5, 24, 16, 16, 58, 638, DateTimeKind.Local).AddTicks(8903),
                            QuoteNumber = "Name 2",
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
